name: Update Homebrew Tap via GitHub Actions

on:
  push:
    branches:
      - main
    paths:
      - 'init.zsh'
      - 'bin/**'
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-tap:
    name: Update Homebrew Tap
    runs-on: macos-latest
    
    steps:
      - name: Checkout shell settings repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for proper versioning
    
      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      
      - name: Determine version
        id: version
        run: |
          # Get the latest commit hash (short)
          COMMIT_HASH=$(git rev-parse --short HEAD)
          # Get current date in YYYYMMDD format
          DATE=$(date +%Y%m%d)
          # Set version as YYYYMMDD.HASH
          VERSION="${DATE}.${COMMIT_HASH}"
          echo "Version will be: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      
      - name: Create Release Tag
        run: |
          VERSION=${{ steps.version.outputs.version }}
          # Check if tag already exists
          if git tag | grep -q "v$VERSION"; then
            echo "Tag v$VERSION already exists, skipping tag creation"
          else
            echo "Creating tag v$VERSION"
            git tag -a "v$VERSION" -m "Release version $VERSION"
            git push origin "v$VERSION"
          fi
      
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: Release v${{ steps.version.outputs.version }}
          body: |
            Automated release of shell settings
            
            Contains the latest shell configuration and scripts as of commit ${{ github.sha }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Checkout homebrew-tools repository
        uses: actions/checkout@v3
        with:
          repository: cajias/homebrew-tools
          path: homebrew-tools
          token: ${{ secrets.TAP_REPO_TOKEN }}
      
      - name: Update Homebrew Formula
        run: |
          VERSION=${{ steps.version.outputs.version }}
          GITHUB_USER=cajias
          SHELL_REPO=zi
          FORMULA_FILE=homebrew-tools/shell-settings.rb
          
          # Calculate SHA256 of the release tarball
          echo "Calculating SHA256 of release tarball..."
          TARBALL_URL="https://github.com/$GITHUB_USER/$SHELL_REPO/archive/refs/tags/v$VERSION.tar.gz"
          SHA256=$(curl -sL "$TARBALL_URL" | shasum -a 256 | awk '{print $1}')
          echo "SHA256: $SHA256"
          
          # Update version and SHA256 in formula
          cd homebrew-tools
          sed -i '' "s|version \".*\"|version \"$VERSION\"|g" shell-settings.rb
          sed -i '' "s|url \".*\"|url \"https://github.com/$GITHUB_USER/$SHELL_REPO/archive/refs/tags/v$VERSION.tar.gz\"|g" shell-settings.rb
          sed -i '' "s|sha256 \".*\"|sha256 \"$SHA256\"|g" shell-settings.rb
          
          # Commit and push changes
          git add shell-settings.rb
          git commit -m "Update shell-settings formula to v$VERSION"
          git push